--Для заполнения базы данными
insert into colors values
(default,'#FF0000','Red'),
(default,'#FFFF00','Yellow'),
(default,'#0000FF','Blue'),
(default,'#000000','Black'),
(default,'#FFFFFF','White');

insert into categories values
(default,'T-Shirts'),
(default,'Shirts'),
(default,'Hoodies'),
(default,'Sweaters'),
(default,'Jackets');

insert into users values 
-- Для авторизации:
-- email: role@gmail.com 
-- password: role
(default, 'user@gmail.com', '$2a$10$GJsSveLkMmft6X0eynpj0OiZfSOPdWbiRLiRDOCi66TiuenUtOgYG', 'false'),
(default, 'admin@gmail.com', '$2a$10$/LsJjVx7eK5dBiHzLqbPU.GgLv4gUzmd9UyaFUTYhIusfHWvKJYdu', 'true');

insert into products values 
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655634158/sfg5fuk6skhlaoilpwj5.jpg', 
'Long Fit Black T-shirt', 
'Long, crew-neck T-shirt in soft jersey with a rounded hem.', 
'13' , 'm', 'XS,S,M,L', 4, 1),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655634431/cdncffzg6bvivfou7vxz.jpg', 
'Relaxed Fit Printed T-shirt', 
'Relaxed-fit T-shirt in soft cotton jersey with a printed design. Crew neck.', 
'30' , 'm', 'S,M,L,XL', 5, 1),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655634628/wighb8uxa2fhclig07ed.jpg', 
'Oversized Fit Patterned Resort Shirt', 
'Oversized shirt in woven cotton fabric with a printed pattern. Resort collar, buttons without placket, and yoke at back. Open chest pocket, short sleeves, and a straight-cut hem.', 
'25' , 'm', 'L,XL,XXL', 2, 2),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655634833/pifw8rbyyry5biyyhdxg.jpg', 
'Slim Fit Stretch Shirt', 
'Shirt in a stretch premium cotton blend. Narrow turn-down collar, smooth button placket, and shaping seams at back. Long sleeves with adjustable buttoning at cuffs. Rounded hem. Slim fit - narrow shoulders and tapered waist for a tailored silhouette.', 
'30' , 'm', 'S', 5, 2),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655635551/itgxuduwdryta8f0aotx.jpg', 
'Relaxed-fit Hoodie', 
'The Hoodie. Relaxed-fit sweatshirt hoodie in cotton-blend fabric with soft, brushed inside. Jersey-lined drawstring hood, kangaroo pocket, and long sleeves. Wide ribbing at cuffs and hem.', 
'30' , 'm', 'M,L', 3, 3),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655635692/e7nz89dydfvns6mhflw3.jpg', 
'Relaxed Fit Half-zip Hoodie', 
'Relaxed-fit sweatshirt hoodie in lightweight cotton fabric with a printed design. ', 
'40' , 'm', 'S,M,L,XL', 4, 3),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655635859/ypr3ufvmewqwvs9jcive.jpg', 
'Merino Wool Turtleneck Sweater', 
'Fine-knit, turtleneck sweater in soft merino wool with ribbing at cuffs and hem.', 
'60' , 'm', 'S,XL', 4, 4),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655636034/kou9u2leeokcv49y4cnb.jpg', 
'Bomber Jacket', 
'Lightweight bomber jacket in woven fabric. Ribbed stand-up collar, zipper at front, and wide ribbing at cuffs and hem.', 
'40' , 'm', 'XS,S', 1, 5),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655636277/s70qyf0fqxubdpg7b35a.jpg', 
'Oversized Denim Jacket', 
'Oversized jacket in thick cotton denim. Collar, metal buttons at front, and yoke at back. Chest pockets with flap and button, welt side pockets, heavily dropped shoulders, and wide sleeves with button at cuffs. Straight-cut hem.', 
'60' , 'w', 'L,S', 3, 5),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655636327/rc1fncjrffoops9lr9an.jpg', 
'Crinkled Cotton Shirt', 
'Relaxed-fit shirt in woven, crinkled cotton fabric. Pointed collar, buttons at front, and long sleeves with button at cuffs. Double-layered yoke at back with slightly forward-facing shoulder seams. Rounded hem, slightly longer at back.', 
'30' , 'w', 'S', 5, 2),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655636482/uzuq44tnxoxwfyqm3hov.jpg', 
'Cotton T-shirt', 
'Straight-cut T-shirt in soft cotton jersey with ribbed crew neck and gently dropped shoulders.', 
'10' , 'w', 'XL,L', 5, 1),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655636529/oksyod3gveq4sv7s71lx.jpg', 
'Modal-blend T-shirt', 
'T-shirt in soft slub jersey made from a modal and cotton blend. Wide neckline and rounded hem.', 
'15' , 'w', 'S', 4, 1),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655636575/aqx0kmyouktmydyuwjf9.jpg', 
'Sweatshirt with Motif', 
'Crew-neck sweatshirt with a motif at front. Long raglan sleeves and ribbing at neckline, cuffs, and hem. Soft, brushed inside.', 
'35' , 'w', 'XXL', 5, 4),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655637011/wjyjjv94mtpuoyv8gohn.jpg', 
'Sweatshirt with Printed Design', 
'Sweatshirt with a printed design. Dropped shoulders, long sleeves, and ribbing at neckline, cuffs, and hem. Soft, brushed inside.', 
'35' , 'w', 'XL', 1, 3),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655637074/uc9moa0ldlupk7tamltq.jpg', 
'Rib-knit Cardigan', 
'Shorter cardigan in a rib-knit Livaeco™ viscose blend. Low-cut V-neck and buttons at front.', 
'30' , 'w', 'M', 3, 4),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655637131/m5kqzzkq6ce0orvlhm1r.jpg', 
'Boxy Cardigan', 
'Boxy cardigan in a fine-knit viscose blend. V-neck, buttons at front, and mock front pockets with button.', 
'70' , 'w', 'L,XL,Xs', 4, 5),
(default, 'http://res.cloudinary.com/malbo/image/upload/v1655637183/igcxdxaagumegddo3e6b.jpg', 
'Oversized Denim Jacket', 
'Oversized jacket in thick cotton denim. Collar, metal buttons at front, and yoke at back. Chest pockets with flap and button, welt side pockets, heavily dropped shoulders, and wide sleeves with button at cuffs. Straight-cut hem.', 
'60' , 'w', 'XL,S', 5, 5);